### ISSUE TITLE
Issues while installing

### ISSUE THREAD

**Issue by hermanfransen** [TeamTobb/MEAN-Typescript-Angular2-Skeleton#1]
Thanks for this great skeleton, a perfect example for me.....

In public/tsconfig.json delete comma at the end of line "experimentalDecorators": true  

Execute typescript compiler 'tsc' two times, one time in root project and one time in folder public  

After this modification it's working though still get errors during compiling the public folder:
controllers/editor.ts(1,61): error TS2307: Cannot find module 'angular2/core'.
controllers/editor.ts(2,55): error TS2307: Cannot find module 'angular2/http'.
controllers/editor.ts(3,48): error TS2307: Cannot find module 'angular2/common'.
controllers/editor.ts(4,32): error TS2307: Cannot find module 'angular2/core'.
controllers/index.ts(1,25): error TS2307: Cannot find module 'angular2/platform/browser'.
controllers/index.ts(3,48): error TS2307: Cannot find module 'angular2/common'.
controllers/index.ts(4,29): error TS2307: Cannot find module 'angular2/http'.

**Comment by hoxmark** [comment]
Thank you for your feedback, happy the skeleton could be to help for you. This will be resolved later tonight. 

We are aware of the errors that comes after compiling the public folder and we will continue to look for a solution to this.
